/* NEOCRAFT — a compact, dependency-free voxel survival prototype. */
const $ = (s) => document.querySelector(s);
const canvas = $('#world'), ctx = canvas.getContext('2d');
const blockInfo = { grass:['🟫','#58934d'], wood:['🪵','#875b36'], stone:['◼','#69716e'], dirt:['▪','#8a613e'], plank:['▤','#c99551'], sword:['🗡','#d5e3e7'], apple:['🍎','#d94f42'] };
const recipes = [{id:'plank', icon:'▤', name:'Planches ×4', cost:{wood:1}, gain:4},{id:'sword',icon:'🗡',name:'Épée en bois',cost:{wood:2,plank:1},gain:1}];
let state, channel, keys={}, last=0, pointer=false, toastTimer, savedBlocks={}, peers={}, touchLook=null;
let language=localStorage.getItem('neocraft-language')||'fr';
const translations={
  fr:{save:'Sauvegarder',load:'Charger',settingsLabel:'PARAMÈTRES',settingsTitle:'Préférences',language:'Langue',codeSpace:'ESPACE CODE',codeLabel:'Code de commandes',activate:'Activer',adminCommands:'COMMANDES ADMINISTRATEUR',codeReady:'Commandes administrateur actives pour cette session.',codeInvalid:'Code invalide.',commandDisabled:'Activez les commandes administrateur dans les paramètres.',commandUnknown:'Commande inconnue. Tapez /help.',commandHelp:'Commandes : /day, /night, /give <objet> <quantité>, /heal, /tp <x> <z>, /clear.',commandDone:'Commande exécutée.',codePlaceholder:'••••'},
  en:{save:'Save',load:'Load',settingsLabel:'SETTINGS',settingsTitle:'Preferences',language:'Language',codeSpace:'CODE AREA',codeLabel:'Command code',activate:'Activate',adminCommands:'ADMIN COMMANDS',codeReady:'Administrator commands are active for this session.',codeInvalid:'Invalid code.',commandDisabled:'Enable administrator commands in settings.',commandUnknown:'Unknown command. Type /help.',commandHelp:'Commands: /day, /night, /give <item> <amount>, /heal, /tp <x> <z>, /clear.',commandDone:'Command executed.',codePlaceholder:'••••'},
  es:{save:'Guardar',load:'Cargar',settingsLabel:'AJUSTES',settingsTitle:'Preferencias',language:'Idioma',codeSpace:'ZONA DE CÓDIGO',codeLabel:'Código de comandos',activate:'Activar',adminCommands:'COMANDOS DE ADMINISTRADOR',codeReady:'Los comandos de administrador están activos para esta sesión.',codeInvalid:'Código no válido.',commandDisabled:'Activa los comandos de administrador en los ajustes.',commandUnknown:'Comando desconocido. Escribe /help.',commandHelp:'Comandos: /day, /night, /give <objeto> <cantidad>, /heal, /tp <x> <z>, /clear.',commandDone:'Comando ejecutado.',codePlaceholder:'••••'}
};
const tr=(key)=>translations[language][key]||translations.fr[key]||key;
function applyLanguage(){document.documentElement.lang=language;$('#languageSelect').value=language;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=tr(el.dataset.i18n));$('#commandInput').placeholder='/help'; if(state) renderHud();}

const hash = (x,z) => { let n=Math.sin(x*127.1+z*311.7)*43758.5453; return n-Math.floor(n); };
const height = (x,z) => Math.floor(2+hash(x,z)*2+Math.sin(x*.16)*1.5+Math.cos(z*.11)*1.2);
const biomeAt = (x,z) => hash(Math.floor(x/14),Math.floor(z/14))>.72 ? 'Forêt de chênes' : hash(Math.floor(x/20),Math.floor(z/20))<.18 ? 'Hautes collines' : 'Plaines';
function init(){
  const seed=$('#seed').value.trim()||'neo', name=$('#playerName').value.trim()||'Explorateur';
  state={seed,name,x:0,z:0,yaw:.4,pitch:0,day:1,time:8,health:10,hunger:10,slot:0,inv:{grass:0,wood:0,stone:0,dirt:0,plank:0,sword:0,apple:2},mobs:[], lastAttack:0,admin:sessionStorage.getItem('neocraft-admin')==='enabled'};
  savedBlocks=JSON.parse(localStorage.getItem('neocraft-blocks-'+seed)||'{}');
  for(let i=0;i<8;i++) state.mobs.push({x:(hash(i,10)-.5)*25,z:(hash(i,22)-.5)*25,hp:3,phase:i});
  applyLanguage(); $('#landing').classList.add('hidden'); $('#game').classList.remove('hidden'); $('#worldName').textContent='MONDE · '+seed.toUpperCase();
  if ('BroadcastChannel' in window) { channel = new BroadcastChannel('neocraft-'+seed); channel.onmessage=e=>receive(e.data); broadcast('hello'); }
  resizeCanvas(); addEventListener('resize',resizeCanvas);
  renderHud(); requestAnimationFrame(loop); notify('Bienvenue dans le monde, '+name+' !');
}
function resizeCanvas(){const ratio=Math.min(window.devicePixelRatio||1,2);canvas.width=innerWidth*ratio;canvas.height=innerHeight*ratio;ctx.setTransform(ratio,0,0,ratio,0,0)}
function broadcast(type, payload={}) { channel?.postMessage({type,payload,name:state.name,id:sessionStorage.tabId||(sessionStorage.tabId=Math.random().toString(36).slice(2))}); }
function receive(m){ if(m.id===sessionStorage.tabId)return; if(m.type==='hello'||m.type==='pos'){peers[m.id]={name:m.name,...m.payload,last:Date.now()};broadcast('pos',{x:state.x,z:state.z})} if(m.type==='block'){savedBlocks[m.payload.key]=m.payload.type;localStorage.setItem('neocraft-blocks-'+state.seed,JSON.stringify(savedBlocks))} }
function worldBlock(x,z){const k=x+','+z; if(savedBlocks[k])return savedBlocks[k]; const h=height(x,z); if(hash(x,z)>.91&&h>2)return 'wood'; return 'grass'}
function loop(t){ const dt=Math.min(.05,(t-last)/1000||0);last=t; update(dt); draw(); requestAnimationFrame(loop); }
function update(dt){
  let speed=(keys.Shift?7:4)*dt, dx=0,dz=0; if(keys.w)dz+=speed;if(keys.s)dz-=speed;if(keys.a)dx-=speed;if(keys.d)dx+=speed;
  state.x+=Math.cos(state.yaw)*dx+Math.sin(state.yaw)*dz;state.z+=Math.sin(state.yaw)*dx-Math.cos(state.yaw)*dz;
  state.time+=dt*.48;if(state.time>=24){state.time-=24;state.day++;notify('Jour '+state.day)}
  state.hunger=Math.max(0,state.hunger-dt*.012); const night=state.time>18||state.time<5;
  state.mobs.forEach(m=>{m.phase+=dt; if(night){let dx=state.x-m.x,dz=state.z-m.z,dist=Math.hypot(dx,dz);if(dist<13){m.x+=dx/dist*dt*.9;m.z+=dz/dist*dt*.9;if(dist<1.4&&Math.random()<dt*.7)hurt()}}});
  if(Math.floor(tick())%2===0) broadcast('pos',{x:state.x,z:state.z}); Object.keys(peers).forEach(k=>{if(Date.now()-peers[k].last>7000)delete peers[k]});
  renderHud();
}
function tick(){return performance.now()/1000}
function project(x,z,y=0){let dx=x-state.x,dz=z-state.z,cy=Math.cos(state.yaw),sy=Math.sin(state.yaw),a=dx*cy+dz*sy,b=-dx*sy+dz*cy;if(b<.25)return null;let f=Math.min(innerWidth,innerHeight)*.8;return{x:innerWidth/2+a/b*f,y:innerHeight*.57-(y-state.pitch*3)/b*f,scale:f/b,depth:b}}
function draw(){let w=innerWidth,h=innerHeight, night=state.time>18||state.time<5, sun=Math.max(0,Math.sin((state.time-6)/12*Math.PI));
  ctx.clearRect(0,0,w,h);let sky=night?'#10233d':`rgb(${Math.floor(68+80*sun)},${Math.floor(125+75*sun)},${Math.floor(150+75*sun)})`;ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);
  ctx.fillStyle=night?'#dfe6b0':'#ffe39a';ctx.beginPath();ctx.arc(w*.77,h*.17,night?18:33,0,Math.PI*2);ctx.fill();
  // horizon and voxel floor; far tiles first make an isometric-like 3D landscape
  for(let z=Math.floor(state.z+23);z>=Math.floor(state.z-3);z--)for(let x=Math.floor(state.x-15);x<=Math.floor(state.x+15);x++){let p=project(x,z,height(x,z));if(!p||p.depth>28)continue;let size=Math.max(2,p.scale*.52), type=worldBlock(x,z);if(type==='air')continue;let shade=Math.max(.35,1-p.depth/45)*(night?.45:1);ctx.fillStyle=shadeColor(blockInfo[type]?.[1]||'#58934d',shade);ctx.fillRect(p.x-size/2,p.y-size/2,size+1,size+1);if(type==='wood'&&p.depth<14){ctx.fillStyle='#5b3524';ctx.fillRect(p.x-size*.18,p.y-size*1.3,size*.36,size*1.3)}}
  drawEntities();
  const grad=ctx.createLinearGradient(0,h*.55,0,h);grad.addColorStop(0,'rgba(8,20,11,0)');grad.addColorStop(1,'rgba(6,17,9,.34)');ctx.fillStyle=grad;ctx.fillRect(0,h*.5,w,h*.5);
}
function drawEntities(){let arr=state.mobs.map(m=>({...m,kind:'mob'})).concat(Object.values(peers).map(p=>({...p,kind:'peer'}))).map(e=>({...e,p:project(e.x,e.z,2)})).filter(e=>e.p).sort((a,b)=>b.p.depth-a.p.depth); for(const e of arr){let s=Math.min(80,e.p.scale*.55), {x,y}=e.p;ctx.fillStyle=e.kind==='mob'?'#5fbd59':'#f3b05b';ctx.fillRect(x-s*.25,y-s,s*.5,s);ctx.fillStyle=e.kind==='mob'?'#2b4e2a':'#233c47';ctx.fillRect(x-s*.32,y-s*1.55,s*.64,s*.6);ctx.fillStyle='#121914';ctx.fillRect(x-s*.16,y-s*1.32,s*.1,s*.1);ctx.fillRect(x+s*.08,y-s*1.32,s*.1,s*.1);if(e.kind==='mob'&&e.p.depth<7){ctx.fillStyle='#251b1b';ctx.fillRect(x-s*.36,y-s*1.8,s*.72,4);ctx.fillStyle='#df5a5a';ctx.fillRect(x-s*.34,y-s*1.8,s*.72*(e.hp/3),4)}}}
function shadeColor(hex,amt){let n=parseInt(hex.slice(1),16),r=(n>>16)*amt,g=((n>>8)&255)*amt,b=(n&255)*amt;return `rgb(${r|0},${g|0},${b|0})`}
function selectedTarget(){return {x:Math.round(state.x+Math.sin(state.yaw)*3),z:Math.round(state.z-Math.cos(state.yaw)*3)}}
function mine(){let now=Date.now();let mob=state.mobs.find(m=>Math.hypot(m.x-state.x,m.z-state.z)<3.2);if(mob){if(now-state.lastAttack<400)return;state.lastAttack=now;mob.hp-=state.inv.sword?2:1;notify(mob.hp<=0?'Monstre vaincu !':'Touché !');if(mob.hp<=0){state.mobs.splice(state.mobs.indexOf(mob),1);state.inv.apple++;}return}let t=selectedTarget(),type=worldBlock(t.x,t.z);if(savedBlocks[t.x+','+t.z]==='air'){notify('Il n’y a rien à miner.');return}state.inv[type]=(state.inv[type]||0)+1;savedBlocks[t.x+','+t.z]='air';broadcast('block',{key:t.x+','+t.z,type:'air'});persistBlocks();notify(blockInfo[type]?.[0]+' '+type+' ajouté à l’inventaire');}
function place(){let item=Object.keys(state.inv).filter(k=>state.inv[k]>0&&['grass','wood','stone','dirt','plank'].includes(k))[state.slot];if(!item){notify('Sélectionnez un bloc disponible.');return}let t=selectedTarget(),key=t.x+','+t.z;if(worldBlock(t.x,t.z)!=='air'){notify('Cet emplacement est occupé.');return}savedBlocks[key]=item;state.inv[item]--;broadcast('block',{key,type:item});persistBlocks();}
function persistBlocks(){localStorage.setItem('neocraft-blocks-'+state.seed,JSON.stringify(savedBlocks))}
function hurt(){state.health=Math.max(0,state.health-1);$('#damage').classList.add('hit');setTimeout(()=>$('#damage').classList.remove('hit'),170);if(!state.health){state.health=10;state.x=state.z=0;notify('Vous réapparaissez au point de départ.')}}
function renderHud(){let inv=state.inv;$('#coords').textContent=`X ${state.x.toFixed(0)} · Y ${height(state.x,state.z)} · Z ${state.z.toFixed(0)}`;$('#biome').textContent=biomeAt(state.x,state.z);$('#dayCount').textContent=String(state.day).padStart(2,'0');let hr=Math.floor(state.time),mn=Math.floor((state.time-hr)*60);$('#timeLabel').textContent=String(hr).padStart(2,'0')+':'+String(mn).padStart(2,'0');$('#clockHand').style.transform=`rotate(${state.time*15-90}deg)`;$('#hearts').textContent='♥'.repeat(Math.ceil(state.health/2))+'♡'.repeat(5-Math.ceil(state.health/2));$('#food').textContent='●'.repeat(Math.ceil(state.hunger/2))+'○'.repeat(5-Math.ceil(state.hunger/2));let slots=['grass','wood','stone','dirt','plank','sword','apple'];$('#hotbar').innerHTML=slots.map((it,i)=>`<button class="slot ${i===state.slot?'active':''}" data-slot="${i}"><span class="key">${i+1}</span>${blockInfo[it][0]}<span class="num">${inv[it]||0}</span></button>`).join('');$('#onlineCount').textContent=(1+Object.keys(peers).length)+' joueur'+(Object.keys(peers).length?'s':'')+' connecté'+(Object.keys(peers).length?'s':'');$('#playerList').innerHTML=`<div class="person"><i class="avatar"></i>${state.name} <small>(vous)</small></div>`+Object.values(peers).map(p=>`<div class="person"><i class="avatar"></i>${p.name}</div>`).join('');let got=inv.wood||0;$('#objectiveText').textContent=got<3?'Récoltez du bois':'Fabriquez une épée';$('#objectiveSub').textContent=got<3?`${got} / 3 bûches`:(inv.sword?'Prêt pour la nuit !':'2 bois + 1 planche');}
function renderRecipes(){ $('#recipes').innerHTML=recipes.map(r=>{let ok=Object.entries(r.cost).every(([k,n])=>state.inv[k]>=n);return `<div class="recipe"><div class="recipe-icon">${r.icon}</div><div><b>${r.name}</b><small>${Object.entries(r.cost).map(([k,n])=>n+' '+k).join(' + ')}</small></div><button data-craft="${r.id}" ${ok?'':'disabled'}>FABRIQUER</button></div>`}).join('') }
function craft(id){let r=recipes.find(x=>x.id===id);if(!r)return;for(let[k,n]of Object.entries(r.cost))if(state.inv[k]<n)return;for(let[k,n]of Object.entries(r.cost))state.inv[k]-=n;state.inv[id]=(state.inv[id]||0)+r.gain;renderRecipes();notify(r.name+' fabriqué !')}
function notify(msg){let t=$('#toast');t.textContent=msg;t.classList.add('toast-show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('toast-show'),2200)}
function setAdmin(active){state.admin=active;sessionStorage.setItem('neocraft-admin',active?'enabled':'');$('#adminCommands').classList.toggle('hidden',!active);$('#codeStatus').textContent=tr(active?'codeReady':'codeInvalid');$('#codeStatus').style.color=active?'#a8e95c':'#ff9c8f';}
function runCommand(value){let [command,...args]=value.trim().toLowerCase().split(/\s+/);if(!command)return;if(!state.admin)return notify(tr('commandDisabled'));if(command==='/help')return notify(tr('commandHelp'));if(command==='/day')state.time=8;else if(command==='/night')state.time=20;else if(command==='/heal')state.health=state.hunger=10;else if(command==='/clear')Object.keys(state.inv).forEach(k=>state.inv[k]=0);else if(command==='/tp'){let [x,z]=args.map(Number);if(!Number.isFinite(x)||!Number.isFinite(z))return notify(tr('commandUnknown'));state.x=x;state.z=z}else if(command==='/give'){let [item,count]=args,n=Math.max(1,Math.min(64,Number(count)||1));if(!blockInfo[item])return notify(tr('commandUnknown'));state.inv[item]=(state.inv[item]||0)+n}else return notify(tr('commandUnknown'));renderHud();notify(tr('commandDone'));}
$('#newWorld').onclick=init;$('#joinWorld').onclick=init;$('#helpBtn').onclick=()=>$('#helpCard').classList.toggle('hidden');$('#closeHelp').onclick=()=>$('#helpCard').classList.add('hidden');$('#closeCraft').onclick=()=>$('#craftCard').classList.add('hidden');$('#settingsBtn').onclick=()=>{$('#settingsCard').classList.toggle('hidden');if(state){$('#adminCommands').classList.toggle('hidden',!state.admin);$('#codeStatus').textContent=state.admin?tr('codeReady'):''}};$('#closeSettings').onclick=()=>$('#settingsCard').classList.add('hidden');$('#languageSelect').onchange=e=>{language=e.target.value;localStorage.setItem('neocraft-language',language);applyLanguage()};$('#applyCode').onclick=()=>{if(!state)return;setAdmin($('#adminCode').value==='2464');$('#adminCode').value=''};$('#saveBtn').onclick=()=>{localStorage.setItem('neocraft-save-'+state.seed,JSON.stringify({x:state.x,z:state.z,inv:state.inv,day:state.day,time:state.time,health:state.health}));persistBlocks();notify('Partie sauvegardée dans ce navigateur.')};$('#loadBtn').onclick=()=>{let s=JSON.parse(localStorage.getItem('neocraft-save-'+state.seed)||'null');if(!s)return notify('Aucune sauvegarde trouvée.');Object.assign(state,s);savedBlocks=JSON.parse(localStorage.getItem('neocraft-blocks-'+state.seed)||'{}');notify('Sauvegarde chargée !')};
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key>='1'&&e.key<='7')state&&(state.slot=+e.key-1);if(e.key.toLowerCase()==='e'&&state){$('#craftCard').classList.toggle('hidden');renderRecipes()}if(e.key==='Enter'&&state&&document.activeElement!==$('#commandInput')){e.preventDefault();$('#commandBar').classList.remove('hidden');$('#commandInput').focus()}if(e.key==='Escape'){document.exitPointerLock();$('#commandBar').classList.add('hidden')}});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);$('#commandInput').addEventListener('keydown',e=>{if(e.key==='Enter'){runCommand(e.currentTarget.value);e.currentTarget.value='';$('#commandBar').classList.add('hidden');canvas.focus()}if(e.key==='Escape'){$('#commandBar').classList.add('hidden');canvas.focus()}}); canvas.onclick=()=>{if(!matchMedia('(pointer: coarse)').matches)canvas.requestPointerLock()};addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas&&state){state.yaw+=e.movementX*.003;state.pitch=Math.max(-1,Math.min(1,state.pitch+e.movementY*.002))}});canvas.addEventListener('pointerdown',e=>{if(!state)return;if(e.pointerType==='touch'){e.preventDefault();touchLook={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId)}});canvas.addEventListener('pointermove',e=>{if(!touchLook||e.pointerId!==touchLook.id||!state)return;state.yaw+=(e.clientX-touchLook.x)*.008;state.pitch=Math.max(-1,Math.min(1,state.pitch+(e.clientY-touchLook.y)*.006));touchLook.x=e.clientX;touchLook.y=e.clientY});canvas.addEventListener('pointerup',e=>{if(touchLook?.id===e.pointerId)touchLook=null});canvas.addEventListener('pointercancel',()=>touchLook=null);canvas.addEventListener('mousedown',e=>{if(!state||e.pointerType==='touch')return;e.preventDefault();if(e.button===0)mine();if(e.button===2)place()});canvas.addEventListener('contextmenu',e=>e.preventDefault());document.querySelectorAll('[data-touch-key]').forEach(button=>{let key=button.dataset.touchKey;button.addEventListener('pointerdown',e=>{e.preventDefault();keys[key]=true;button.setPointerCapture(e.pointerId)});['pointerup','pointercancel','lostpointercapture'].forEach(type=>button.addEventListener(type,()=>keys[key]=false))});document.querySelectorAll('[data-touch-action]').forEach(button=>button.addEventListener('pointerdown',e=>{e.preventDefault();if(!state)return;let action=button.dataset.touchAction;if(action==='mine')mine();if(action==='place')place();if(action==='craft'){$('#craftCard').classList.toggle('hidden');renderRecipes()}}));$('#hotbar').onclick=e=>{let b=e.target.closest('[data-slot]');if(b)state.slot=+b.dataset.slot};$('#recipes').onclick=e=>{let b=e.target.closest('[data-craft]');if(b)craft(b.dataset.craft)};

applyLanguage();
